### ISSUE TITLE
zapslog stabilization tracking issue

### ISSUE THREAD

**Issue by abhinav** [uber-go/zap#1333]
This issue tracks everything we need to do before zapslog can be moved to the main go.uber.org/zap module.

- [ ] Add stack traces #1329
- [ ] Test with slogtest, fix all failures
- [ ] Ensure adequate test coverage
- [ ] Delete exp-based implementation
- [ ] Add a zapslog.Core that writes Zap logs to a slog.Handler

**Comment by arukiidou** [comment]
I would like to contribute  zapslog GA.

> zapslog: Add a zapslog.Core that writes Zap logs to a slog.Handler
> We may want to rename zapslog.Options to HandlerOptions when we do this.

Can you tell us more about this?

**Comment by abhinav** [comment]
> I would like to contribute zapslog GA.
> 
> > zapslog: Add a zapslog.Core that writes Zap logs to a slog.Handler
> > We may want to rename zapslog.Options to HandlerOptions when we do this.
> 
> Can you tell us more about this?

Hello! Yes!

Okay, so right now, zapslog takes a Zap core, and returns a slog handler. `func NewHandler(zapcore.Core) slog.Handler`.
That's for applications that are already using Zap, and want to connect to a library that's using slog, to have the library feed their slog logs into their Zap handler.

The proposal was for the reverse: your application is using slog, and you want to use a library that uses Zap, so you want Zap to feed into your slog as the backend. Basically, `func NewCore(slog.Handler) zapcore.Core`.

Thinking about it out loud, though I don't know if this is actually necessary. @mway @prashantv @sywhang @r-hang What do y'all think?

On the second point: if this was added, then we'd want to rename the `Option` type to `HandlerOption` because we'd need another Option type (CoreOption) for the `NewCore` function.

One thing we could do is defer implementing NewCore until the need presents itself, but rename Option to HandlerOption anyway so that if/when that happens, we have the "option" name free.

**Comment by arukiidou** [comment]
- Is this what you mean?: #1411
If so, it seems to me that we can submit this as a separate item now.

That way we could move zapslog to the root moduke without having to change anything, and easier to migrate from exp for users..

**Comment by abhinav** [comment]
Yeah, I think following the rename, we can defer adding `NewCore` to when we need it. 
That PR looks good! Thanks!

**Comment by arukiidou** [comment]
Started working on custom mapping.

- #1412
  - #1413

**Comment by arukiidou** [comment]
- Added #1413, please take a look?

**Comment by mblaschke** [comment]
any estimation when this will be finished?

**Comment by mblaschke** [comment]
any progress?

**Comment by nick4fake** [comment]
What is the current state in terms of stability?
